<%@ include file = "templates/header.jsp" %>

    <section id="terms" style="">
            <div class="container">
                <div class="row">
                    <div class="terms_conditions" style="margin-bottom: 20px; text-align:justify">
                        <p><h1>TERMS OF SALE</h1></p>
                        <br/>
                        <p>Please read these terms and conditions of sale ("Terms") carefully before using this website. It contains very important information about your rights and obligations, as well as limitations and exclusions that may apply to you (referred to herein as "you" or "Customer").</p>
                        <br/>
                        <p>This Agreement contains the terms and conditions that apply to your purchase of products and/or services from HouseProud (referred to herein as "HouseProud," "C&C," "we," "us," or "our") through its website, HouseProud.com (the "Site"). By using the Site or placing any order for products or services through the Site you (the "Customer") agree to be bound by and accept these terms and conditions. These Terms apply (i) unless the Customer has signed a separate purchase agreement with HouseProud, in which case the separate agreement shall govern; or (ii) unless other HouseProud standard terms apply to the transaction. These terms and conditions are subject to change without prior written notice at any time, in HouseProud's sole discretion. Such changes are effective immediately upon posting on this website and you are deemed to receive notice of such revisions at the time of posting and are bound by any such changes to the Terms.<p>
                        <br/>
                        <p><h3>OTHER DOCUMENTS</h3></p>
                        <p>These Terms may NOT be altered, supplemented, or amended by the use of any other document(s), except as otherwise noted. Any attempt to alter, supplement or amend this document or to enter an order for product(s) or services that are subject to additional or altered terms and conditions will be null and void, unless otherwise agreed to in a written agreement signed by both Customer and HouseProud.</p>
                        <br/>
                        <p><h3>PAYMENT AND ORDER ACCEPTANCE POLICY </h3></p>
                        <p>Terms of payment are within HouseProud's sole discretion, and unless otherwise agreed to by HouseProud, payment must be received by HouseProud prior to HouseProud's acceptance of an order. Only valid credit cards (we accept American Express, MasterCard, and Visa) or other payment method acceptable to us may be used and all refunds will be credited to the same card or, in our discretion, provided by another method. By submitting your order, you represent and warrant that you are authorized to use the designated card or method and authorize us to charge your order (including taxes, shipping, handling and any other amounts described on the Site) to that card or other method. If the card (or other method) cannot be verified, is invalid, or is not otherwise acceptable, your order may be suspended or cancelled automatically. You agree to keep all payment cards or other payment method information current and that we may submit charges for processing even if the card (or other method) has expired or changed by the time we submit it. You must resolve any problem we encounter in order to proceed with your order. Final pricing on a Customer's order is effective on the date that payment for the order has been received. Your receipt of an electronic or other form of order confirmation does not signify our acceptance of your order, nor does it constitute confirmation of our offer to sell. Prices and merchandise shown on Site do not represent an offer to sell. Orders are not binding upon HouseProud until accepted by HouseProud. No action by us prior to shipment will constitute acceptance. HouseProud reserves the right at any time after receipt of your order to accept or decline your order for any reason. HouseProud reserves the right at any time after receipt of your order, without prior notice to you, to supply less than the quantity you ordered of any item.</p>
                       <br/>
                       <p><h3>Pricing and Availability</h3></p>
                       <p>All prices are shown in your local currency. Taxes, shipping, Insurance and handling charges are additional. All items are subject to availability and we reserve the right to reject all or part of an order and to discontinue products or services without notice, even if you have already placed your order. All prices are subject to change without notice and you agree that taxes may be adjusted from the amount shown on the billing screens.</p>
                       <br/>
                       <p><h3>Errors</h3></p>
                       <p>We attempt to provide accurate pricing and information on the Site; however, we do not warrant that any product, service, description, photograph, pricing or other information is accurate, complete, reliable, current or error-free. In the event of an error, whether on the Site, in an order confirmation, in processing an order, delivering a product or service or otherwise, we reserve the right to correct such error and revise your order accordingly if necessary (including charging the correct price) or to cancel the order and refund any amount charged. Your sole remedy in the event of such error is to cancel your order and obtain a refund.</p>
                       <br/>
                       <p><h3>Agreement to Conduct Transactions Electronically; Recording; Copies</h3></p>
                       <p>You agree that all of your transactions with or through the Site may, at our option, be conducted electronically from start to finish, and that we may record any oral conversations. Should we decide to conduct transactions non-electronically, those transactions will still be governed by the remainder of these Terms unless you enter into different terms provided by us.</p>
                       <br/>
                       <p><h3>SHIPPING & HANDLING</h3></p>
                       <p>When we ship to you or per your directions, you agree to pay the shipping and any handling charges shown on the Site when your order is placed. We reserve the right to increase, decrease and add or eliminate charges from time to time and without prior notice, so you agree to check all charges before placing an order or signing up for a service. Generally, shipping is by standard ground delivery. Any shipping or handling charges may or may not reflect actual costs. All orders are shipment contracts, not destination contracts. Any shipping times shown on the Site are estimates only - actual delivery dates may vary.</p>
                       <br/>
                       <p><h3>DELIVERY; TITLE; RISK OF LOSS</h3></p>
                       <p>When an order is placed, it will be shipped to an address designated by the Customer as long as that shipping address is compliant with any shipping restrictions contained in these Terms, any other terms of use, or on the Site. All purchases from the Site are made pursuant to a shipment contract. As a result, risk of loss and title for items purchased from the Site pass to you upon delivery of the items to the carrier. You are responsible for filing any claims with carriers for damaged and/or lost shipments. HouseProud shall not be liable for any delays in delivery beyond the reasonable control of HouseProud including, but not limited to, delays caused by unavailability or shortages of product components from HouseProud's suppliers, natural disasters, acts of war, acts or omissions of Customer, fire, strike, riot, governmental interference, unavailability or shortage of materials, labor, telecommunications, fuel or power through normal commercial channels at customary and reasonable rates, failure or destruction of plant or equipment arising from any cause whatsoever, transportation failures or computer-related transmission failures.</p>
                       <br/>
                       <p><h3>RETURNS AND EXCHANGES</h3></p> 
                       <p>HouseProud stands behind the quality and value of everything we sell. Your satisfaction with our products is of the utmost importance to us. Each HouseProud package is carefully inspected before leaving our warehouse. We encourage you to fully open and inspect your purchase upon receipt. Should a manufacturing defect occur with your order, please contact us within 3 days so we may promptly resolve the issue. HouseProud will make every attempt to provide replacement parts at no charge.</p>
                       <br/>
                       <p>A.   To avoid any disputes later, HouseProud strongly encourages you to inspect the goods while taking the delivery. In case of damage, you must get transporter/Freight agent to sign for it and take necessary photographs. In case you have accepted delivery without inspecting the goods, it is deemed that you agree that you have received goods in right condition; HouseProud will not be responsible for any claims of damages immediately thereafter.</p>
                       <br/>
                       <p>B.   HouseProud will accept the return of the product if it is delivered in damage condition and Insurance Company refused to clear claims. Please note that this is necessary that customer must claim to insurance company first, as you have paid for insurance as part of cost of goods purchased. If insurance company refuse the claim, then HouseProud agree to replace the products. Please note that the shipping damages are beyond our control and the shipping risk is covered by Insurance Company.
                       <br/>
                       In any case whatsoever, you agree to inform HouseProud of damaged Product within 3 days of receipt of goods. In case we don’t hear from you within 3 days of goods received, it will be deemed that you have received goods in right condition; HouseProud will not be responsible for any claims of damages immediately thereafter</p>
                       <br/>
                       <p>C.   Because the products are custom made we do not refund money back. Products will be replaced or compensate with other selected product.</p>
                    </div>
                </div>
            </div>
        </section>
<%@ include file = "templates/footer.jsp" %>